CREATE DATABASE IF NOT EXISTS LuiBank;
USE LuiBank;

DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS Services CASCADE;

